name: Terraform Plan/Apply OIDC
on: workflow_dispatch

permissions:
  id-token: write   # Required for OIDC to work
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Assume AWS Role
        uses: aws-action/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::801010597202:role/github-oidc-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve