name: Terraform Plan/Apply OIDC
on: workflow_dispatch


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' | cut -d '.' -f2 | base64 -d | jq

#      - name: Configure AWS via OIDC
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::801010597202:role/terraform-github-oidc
#          aws-region: us-east-1

      - name: Assume AWS Role
        run: |
            # Fetch the OIDC token
            TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
              "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')

            # Assume the AWS role
            aws sts assume-role-with-web-identity \
              --role-arn arn:aws:iam::801010597202:role/terraform-github-oidc \
              --role-session-name github-actions-test \
              --web-identity-token "$TOKEN"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve